### ISSUE TITLE
`StateSpace.new` silently returns None if `max_expanded` is reached

### ISSUE THREAD

**Issue by DillonZChen** [simon-stahlberg/mimir#4]
This can happen for example by calling [the example script](https://github.com/simon-stahlberg/mimir/blob/main/docs/examples/goal_matcher.py) on a problem with a very large state space. A log statement would be nice to detect this.

**Comment by DillonZChen** [comment]
I just realised that's what the line at 24 in the script does but this does not this never gets called because of line 23.

**Comment by simon-stahlberg** [comment]
Thank you for your interest and comment. Using `state_space` before checking was indeed an oversight. :-)

Dominik and I are currently rewriting a large portion of Mimir to improve the interface and produce better error messages. We welcome any feedback. In the next version, we will consider throwing an error instead of returning `None`, and we will try to use a constructor instead of `.new`, if possible.
